/**
 * This file was generated by the JPA Modeler
 */ 

package br.edu.ifpb.dac.shared.entity;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;


/**
 * @author Laerton_note
 */

@Entity
public class Candidato extends Usuario implements Serializable { 
    private double nota;
    private String curriculo;
    
    @OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.MERGE)
    private List<Preferencia> preferencias = new LinkedList<>();
    
    @OneToMany(mappedBy = "inscrito", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    private List<Inscricao> inscricoes = new LinkedList<>();

    public Candidato(double nota, String curriculo, String email, String senha, String nome) {
        super(email, senha, nome);
        this.nota = nota;
        this.curriculo = curriculo;
    }

        
    public Candidato() 
    {
        
    }
    
    
    public List<Preferencia> getPreferencias() {
        return preferencias;
    }

    public void setPreferencias(List<Preferencia> preferencias) {
        this.preferencias = preferencias;
    }


    
    public void addPreferencia(Preferencia preferencia){
        preferencias.add(preferencia);
    }
    
    public void removePreferencia(Preferencia preferencia){
        preferencias.remove(preferencia);
    }
    
    public void addInscricao(Inscricao insc){
        insc.setInscrito(this);
        inscricoes.add(insc);
    }
    
    public void removeInscricao(Inscricao insc){
        inscricoes.remove(nota);
    }
    
    public List<Inscricao> getInscricoes() {
        return inscricoes;
    }

    public void setInscricoes(List<Inscricao> inscricoes) {
        this.inscricoes = inscricoes;
    }
    
    

    public double getNota() {
        return this.nota;
    }

    public void setNota(double nota) {
        this.nota = nota;
    }

    public String getCurriculo() {
        return this.curriculo;
    }

    public void setCurriculo(String curriculo) {
        this.curriculo = curriculo;
    }



}
