/**
 * This file was generated by the JPA Modeler
 */ 

package br.edu.ifpb.dac.shared.entity;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * @author Laerton_note
 */

@Entity
public class Funcionario extends Usuario implements Serializable { 

    @Basic
    @Enumerated(EnumType.STRING)
    private FuncionarioType cargo;

    public Funcionario() {
    }

    public Funcionario(FuncionarioType cargo, String email, String senha, String nome) {
        super(email, senha, nome);
        this.cargo = cargo;
    }

   
    
    
    @OneToMany(mappedBy = "avaliador", cascade = CascadeType.ALL)
    private List<Avaliacao> avaliacoes = new LinkedList<>();

    public List<Avaliacao> getAvaliacoes() {
        return avaliacoes;
    }

    public void setAvaliacoes(List<Avaliacao> avaliacoes) {
        this.avaliacoes = avaliacoes;
    }

    public FuncionarioType getCargo() {
        return this.cargo;
    }

    public void setCargo(FuncionarioType cargo) {
        this.cargo = cargo;
    }


}
