/**
 * This file was generated by the JPA Modeler
 */ 

package br.edu.ifpb.dac.shared.entity;

import java.io.Serializable;
import java.util.LinkedList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;



/**
 * Classe cuida dos dados de uma vaga
 * @author Laerton_note
 */

@Entity
public class Vaga implements Serializable { 

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long id;

    
    @Basic
    private String descricao;

    @OneToMany(fetch = FetchType.EAGER)
    private List<Preferencia> preferencias = new LinkedList<>();
    
    @OneToMany(fetch = FetchType.EAGER)
    private List<Inscricao> inscritos = new LinkedList<>();

    public Vaga() {
    }

    public Vaga( String descricao) {
        this.descricao = descricao;
        
    }

    public List<Inscricao> getInscritos() {
        return inscritos;
    }

    public void setInscritos(List<Inscricao> inscritos) {
        this.inscritos = inscritos;
    }

    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    public void addPreferencia(Preferencia preferencia){
        preferencias.add(preferencia);
    }
    
    public void removePreferencia(Preferencia preferencia){
        preferencias.remove(preferencia);
    }
    
    public List<Preferencia> getPreferencias() {
        return preferencias;
    }

    public void setPreferencias(List<Preferencia> preferencias) {
        this.preferencias = preferencias;
    }




}
